// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcR1Y9CJSBDaEL-1Rp142kP7-3wP7IgU0',
    appId: '1:575910676693:web:e28730cbbabce570a1ba5c',
    messagingSenderId: '575910676693',
    projectId: 'fir-flutter-codelab-d3bb2',
    authDomain: 'fir-flutter-codelab-d3bb2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d3bb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavw0MAtWa13rnSgxG0OcUwH5xweah6Fs',
    appId: '1:575910676693:android:8fc94fe40b8133cca1ba5c',
    messagingSenderId: '575910676693',
    projectId: 'fir-flutter-codelab-d3bb2',
    storageBucket: 'fir-flutter-codelab-d3bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZaglYJTWY6j6iIClmPcWrDEfDg0mnybM',
    appId: '1:575910676693:ios:b3acf19c9ad0bdeda1ba5c',
    messagingSenderId: '575910676693',
    projectId: 'fir-flutter-codelab-d3bb2',
    storageBucket: 'fir-flutter-codelab-d3bb2.appspot.com',
    iosClientId: '575910676693-ac9brqll5v2jitri1girjh2b3l2b6d99.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGetToKnowFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZaglYJTWY6j6iIClmPcWrDEfDg0mnybM',
    appId: '1:575910676693:ios:b3acf19c9ad0bdeda1ba5c',
    messagingSenderId: '575910676693',
    projectId: 'fir-flutter-codelab-d3bb2',
    storageBucket: 'fir-flutter-codelab-d3bb2.appspot.com',
    iosClientId: '575910676693-ac9brqll5v2jitri1girjh2b3l2b6d99.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGetToKnowFlutter',
  );
}
